"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { BriefcaseBusiness, ChevronRight, Code2, Download, FileText, Folder, Github, GraduationCap, HeartPulse, Linkedin, Mail, Menu, Minus, Terminal, X } from "lucide-react";
import { siAmazon, siGithub, siGooglecolab, siMysql, siNumpy, siPandas, siPython, siScikitlearn, siTableau } from "simple-icons";

const portrait="/portrait.jpeg", resume="/Swaroop_Resume.pdf";
const links={github:"https://github.com/Swarooprevu",linkedin:"https://www.linkedin.com/in/swaroop-revu/",email:"mailto:swarooprevu@gmail.com"};
type WindowId="desktop"|"welcome"|"skills"|"projects"|"journey"|"contact";
type Point={x:number;y:number};
const defaults:Record<WindowId,Point>={desktop:{x:145,y:86},welcome:{x:74,y:356},skills:{x:710,y:84},projects:{x:505,y:360},journey:{x:170,y:420},contact:{x:875,y:370}};
const skills=["SQL","Python","Power BI","Excel","MySQL","Pandas","NumPy","Tableau","AWS","scikit-learn","Google Colab"];
const projects=[
 {name:"NIFTY Sector Performance",file:"nifty_sector_analysis.exe",tools:"SQL · Power BI · Excel · MySQL",copy:"17K+ records across six NIFTY sector indices. Built SQL ETL and a 4-page Power BI dashboard to compare return, CAGR, volatility and drawdown.",result:"NIFTY Auto was the highest-return sector; FMCG was the most resilient."},
 {name:"HR Analytics Dashboard",file:"workforce_signals.pbi",tools:"Excel · Power BI · DAX",copy:"A workforce analytics dashboard for 311 employees, with validated KPIs for retention, compensation and workforce planning.",result:"Identified 40.15% attrition and the highest-risk departments."},
 {name:"MindTrack Prediction",file:"mindtrack_model.py",tools:"Python · TabNet · scikit-learn",copy:"Evaluated models on PHQ-9 and wearable data after preprocessing and SMOTE balancing.",result:"TabNet reached 92.7% on PHQ-9 and 96.1% on wearable data."}
];
function Brand({name}:{name:string}){const icons:Record<string,{path:string;hex:string}>={Python:siPython,MySQL:siMysql,Pandas:siPandas,NumPy:siNumpy,Tableau:siTableau,AWS:siAmazon,"scikit-learn":siScikitlearn,"Google Colab":siGooglecolab,GitHub:siGithub};const icon=icons[name];return icon?<svg viewBox="0 0 24 24" className="brand"><path d={icon.path} fill={`#${icon.hex}`}/></svg>:<span className="brand fallback">{name.slice(0,1)}</span>}
function ShortcutIcon({type}:{type:"computer"|"bin"|"txt"|"folder"|"cmd"|"mail"}){return <span className={`shortcut-icon ${type}`}>{type==="computer"?"▣":type==="bin"?"♻":type==="cmd"?"C:\\_":type==="mail"?"✉":type==="txt"?"▤":""}</span>}
function WindowFrame({id,title,icon,position,z,minimized,onFocus,onMinimize,onClose,onPositionChange,children}:{id:WindowId;title:string;icon:React.ReactNode;position:Point;z:number;minimized:boolean;onFocus:()=>void;onMinimize:()=>void;onClose:()=>void;onPositionChange:(point:Point)=>void;children:React.ReactNode}){const [drag,setDrag]=useState<{start:Point;origin:Point}|null>(null);useEffect(()=>{const move=(e:PointerEvent)=>{if(!drag)return;onPositionChange({x:Math.max(10,drag.origin.x+e.clientX-drag.start.x),y:Math.max(55,drag.origin.y+e.clientY-drag.start.y)})};const up=()=>setDrag(null);window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)}},[drag,onPositionChange]);const objects:Record<WindowId,string>={desktop:"5 object(s)",welcome:"3 object(s)",skills:"11 object(s)",projects:"3 object(s)",journey:"4 object(s)",contact:"3 object(s)"};return <section id={`window-${id}`} className={`desk-window win-${id} ${minimized?"minimized":""}`} style={{left:position.x,top:position.y,zIndex:z}} onPointerDown={onFocus}><header onPointerDown={e=>{if((e.target as HTMLElement).closest("button"))return;setDrag({start:{x:e.clientX,y:e.clientY},origin:position})}}><span className="window-title">{icon}{title}</span><div className="window-actions"><button onClick={onMinimize} aria-label="Minimize"><Minus/></button><button onClick={onClose} aria-label="Close"><X/></button></div></header><div className="menu-bar">File&nbsp;&nbsp; Edit&nbsp;&nbsp; View&nbsp;&nbsp; Options&nbsp;&nbsp; Help</div><div className="window-content">{children}</div><footer className="status-bar">{objects[id]}</footer></section>}
export default function Home(){const [open,setOpen]=useState<Record<WindowId,boolean>>({desktop:true,welcome:true,skills:true,projects:false,journey:false,contact:false});const [positions,setPositions]=useState<Record<WindowId,Point>>(defaults);const [min,setMin]=useState<Partial<Record<WindowId,boolean>>>({});const [layers,setLayers]=useState<Record<WindowId,number>>({desktop:1,welcome:2,skills:3,projects:4,journey:5,contact:6});const [selected,setSelected]=useState(0);const [now,setNow]=useState("");useEffect(()=>{const refresh=()=>setNow(new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date()));refresh();const id=window.setInterval(refresh,1000);return()=>window.clearInterval(id)},[]);const openWin=(id:WindowId)=>{const sizes:Record<WindowId,number>={desktop:680,welcome:560,skills:540,projects:690,journey:600,contact:500};setPositions(v=>({...v,[id]:{x:Math.max(14,Math.round((window.innerWidth-sizes[id])/2)),y:Math.max(72,Math.round((window.innerHeight-390)/2))}}));setMin(v=>({...v,[id]:false}));setOpen(v=>({...v,[id]:true}));setLayers(v=>({...v,[id]:Math.max(...Object.values(v))+1}))};const focus=(id:WindowId)=>setLayers(v=>({...v,[id]:Math.max(...Object.values(v))+1}));const move=(id:WindowId)=>(point:Point)=>setPositions(v=>({...v,[id]:point}));return <main className="desktop"><div className="desktop-grid"/><div className="desktop-icons"><button onClick={()=>openWin("welcome")}><ShortcutIcon type="folder"/><span>About</span></button><button onClick={()=>openWin("projects")}><ShortcutIcon type="folder"/><span>Projects</span></button><button onClick={()=>openWin("skills")}><ShortcutIcon type="folder"/><span>Skills</span></button><button onClick={()=>openWin("journey")}><ShortcutIcon type="folder"/><span>Journey</span></button><button onClick={()=>openWin("contact")}><ShortcutIcon type="folder"/><span>Contact</span></button></div>
{open.desktop&&<WindowFrame id="desktop" title="Desktop" icon={<Folder/>} position={positions.desktop} z={layers.desktop} minimized={!!min.desktop} onFocus={()=>focus('desktop')} onMinimize={()=>setMin(v=>({...v,desktop:!v.desktop}))} onClose={()=>setOpen(v=>({...v,desktop:false}))} onPositionChange={move("desktop")}><div className="desktop-folder">{([['About','welcome'],['Projects','projects'],['Skills','skills'],['Journey','journey'],['Contact','contact']] as const).map(([label,id])=><button onClick={()=>openWin(id)} key={label}><ShortcutIcon type="folder"/><span>{label}</span></button>)}</div></WindowFrame>}
{open.welcome&&<WindowFrame id="welcome" title="welcome_to_my_portfolio.txt" icon={<FileText/>} position={positions.welcome} z={layers.welcome} minimized={!!min.welcome} onFocus={()=>focus('welcome')} onMinimize={()=>setMin(v=>({...v,welcome:!v.welcome}))} onClose={()=>setOpen(v=>({...v,welcome:false}))} onPositionChange={move("welcome")}><div className="welcome-content"><div><p className="eyebrow">HI! I&apos;M</p><h1>Narasimha<br/>Swaroop Revu</h1><p>I turn raw data into useful answers—through SQL pipelines, Power BI dashboards, and predictive models.</p><div className="welcome-actions"><a href={resume} download>Download résumé <Download/></a><button onClick={()=>openWin("contact")}>Say hello <ChevronRight/></button></div></div><div className="portrait-panel"><Image src={portrait} alt="Narasimha Swaroop Revu" fill sizes="280px"/></div></div></WindowFrame>}
{open.skills&&<WindowFrame id="skills" title="D:\WIN\system32\cmd.exe" icon={<Terminal/>} position={positions.skills} z={layers.skills} minimized={!!min.skills} onFocus={()=>focus('skills')} onMinimize={()=>setMin(v=>({...v,skills:!v.skills}))} onClose={()=>setOpen(v=>({...v,skills:false}))} onPositionChange={move("skills")}><div className="terminal"><p>Microsoft(R) Windows DOS</p><p>(C)Copyright Microsoft Corp 1990-1995.</p><p>C:\Users\Swaroop&gt; <span>cd skills_and_software</span></p><p>C:\Users\Swaroop\skills_and_software&gt; <span>dir</span></p><div className="skill-output">{skills.map(s=><span key={s}><Brand name={s}/>{s}</span>)}</div><p className="prompt">C:\Users\Swaroop\skills_and_software&gt; <i/></p></div></WindowFrame>}
{open.projects&&<WindowFrame id="projects" title="some stuff i&apos;ve done" icon={<Folder/>} position={positions.projects} z={layers.projects} minimized={!!min.projects} onFocus={()=>focus('projects')} onMinimize={()=>setMin(v=>({...v,projects:!v.projects}))} onClose={()=>setOpen(v=>({...v,projects:false}))} onPositionChange={move("projects")}><div className="project-explorer gallery"><article><h2>projects + work</h2><p>I build data products that turn messy information into clear decisions. Here are a few examples of the work I&apos;ve done.</p><div className="project-grid">{projects.map((p,i)=><button className={selected===i?"selected":""} onClick={()=>setSelected(i)} key={p.name}><span className={`project-tile tile-${i}`}/><b>{p.name}</b></button>)}</div></article><div className="project-detail-card"><p className="explorer-label">SELECTED / 0{selected+1}</p><strong>{projects[selected].name}</strong><p>{projects[selected].copy}</p></div></div></WindowFrame>}
{open.journey&&<WindowFrame id="journey" title="career_history.log" icon={<BriefcaseBusiness/>} position={positions.journey} z={layers.journey} minimized={!!min.journey} onFocus={()=>focus('journey')} onMinimize={()=>setMin(v=>({...v,journey:!v.journey}))} onClose={()=>setOpen(v=>({...v,journey:false}))} onPositionChange={move("journey")}><div className="timeline"><p><GraduationCap/><b>2022 - 2026</b> B.Tech Computer Science & Engineering, GITAM</p><p><BriefcaseBusiness/><b>Apr - Jun 2025</b> AI/ML Intern, AWS via EduSkills</p><p><BriefcaseBusiness/><b>Jun - Aug 2025</b> System Administrator Intern, ServiceNow</p><p><HeartPulse/><b>NOW</b> Seeking entry-level Data Analyst roles</p></div></WindowFrame>}
{open.contact&&<WindowFrame id="contact" title="get_in_touch.txt" icon={<FileText/>} position={positions.contact} z={layers.contact} minimized={!!min.contact} onFocus={()=>focus('contact')} onMinimize={()=>setMin(v=>({...v,contact:!v.contact}))} onClose={()=>setOpen(v=>({...v,contact:false}))} onPositionChange={move("contact")}><div className="contact-file"><h2>LET&apos;S TALK.</h2><p>I&apos;m seeking entry-level data analyst roles where careful analysis, curiosity, and clear communication can make a useful difference.</p><div className="contact-social"><a href={links.linkedin} target="_blank" rel="noreferrer"><span className="social-pixel linkedin"><Linkedin/></span><u>LinkedIn</u></a><a href={links.github} target="_blank" rel="noreferrer"><span className="social-pixel github"><Github/></span><u>GitHub</u></a><a href={links.email}><span className="social-pixel email"><Mail/></span><u>Email</u></a></div></div></WindowFrame>}
<footer className="taskbar"><button className="start" onClick={()=>openWin("desktop")}><Menu/> Start</button>{(Object.keys(open) as WindowId[]).filter(k=>open[k]).map(k=><button key={k} className={min[k]?"min":""} onClick={()=>setMin(v=>({...v,[k]:false}))}>{k==="skills"?<Terminal/>:k==="projects"?<Folder/>:k==="contact"?<FileText/>:k==="desktop"?<Folder/>:<FileText/>}{k==="welcome"?"read_me.txt":k==="skills"?"skills.cmd":k==="projects"?"projects":k==="journey"?"career_history.log":k==="contact"?"get_in_touch.txt":"Desktop"}</button>)}<span>{now}</span></footer></main>}
